### ISSUE TITLE
"Warning: Object prototype may only be an Object or null" on run with grunt

### ISSUE THREAD

**Issue by benlachman** [ackme/WiConnectWebApp#1]
After cloning the repo and installing per the directions I get:

```
$ grunt
…
Running "server" task
Warning: Object prototype may only be an Object or null: /Users/ben/Development/Sense/WiConnectWebApp/out/setup Use --force to continue.

Aborted due to warnings.
```

Basically the generation task works fine, but the server setup fails. Specifically, `app.use(express.static('/setup', __dirname + '/out/setup'))` is the failure line. It seems like it tries to do an Object.create with the second arg and since that's a path instead of a object prototype, it fails,

Heres the more verbose output:

```
/Users/ben/Development/Sense/WiConnectWebApp/node_modules/express/node_modules/serve-static/index.js:47
  var opts = Object.create(options || null)
                    ^
TypeError: Object prototype may only be an Object or null: /Users/ben/Development/Sense/WiConnectWebApp/out/setup
    at Function.create (native)
    at Function.serveStatic (/Users/ben/Development/Sense/WiConnectWebApp/node_modules/express/node_modules/serve-static/index.js:47:21)
    at Object.<anonymous> (/Users/ben/Development/Sense/WiConnectWebApp/server.js:12:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by mitchmcginnis** [comment]
Changing lines 12 and 13 to 
app.use(express.static( __dirname + '/out/setup'));
app.use(express.static( __dirname + '/out/webapp'));
fixed the issue for me.

**Comment by mitchmcginnis** [comment]
Change lines 12 & 13 in server.js to
     app.use(express.static( __dirname + '/out/setup'));
     app.use(express.static( __dirname + '/out/webapp'));
